### ISSUE TITLE
Signup Functionality not working for student and alumni

### ISSUE THREAD

**Issue by AnushkaGupta2003** [MohammedMusharraf11/Alumni-Connect#11]
![Screenshot (790)](https://github.com/user-attachments/assets/e351eceb-147f-4b36-9f03-c18acc7b86d6)
Assign me this issue to rectify the backend, frontend

**Comment by AnushkaGupta2003** [comment]
During the signup I faced problem as mandatory fields were not marked and the error shown were of no help. I will update the UI.
There were no steps on how to validate a alumni so any alumni will not have idea how to contact the admin.

**Comment by MohammedMusharraf11** [comment]
Actually backend isn't configured for this 
you can use this link 
https://alumni-connect-99.onrender.com
