### ISSUE TITLE
Follow/Unfollow feature

### ISSUE THREAD

**Issue by AnushkaGupta2003** [MohammedMusharraf11/Alumni-Connect#12]
I will work on Follow  unfollow feature . My approach will be to first make a model that will store which user follows which student or alumni. Then code up routes and write mongodb query.

**Comment by MohammedMusharraf11** [comment]
Sure you can work on it

**Comment by AnushkaGupta2003** [comment]
I have some queries. Please answer them so that I can start working asap.
1 - When a user wants to follow someone that is there way to distinguish that they are student or alumni.
2 -  Will admin have follow /unfollow feature ?
3 - I will make two separate models one will store a student follows student , other will have student follows alumni and for this I need to know thhe answer to 1st question

**Comment by MohammedMusharraf11** [comment]
There is key called role in alumni model and this role will be automatically assigned when the alumni registers from the Alumni Registration page.
Similarly I will update the model for student as well.
Nope admin won't have the access for that.
You can go ahead (:

**Comment by AnushkaGupta2003** [comment]
Review the code and please merge this  feature. I wish to work on more features and updates in the future.
