### ISSUE TITLE
Enhancement: UI doesn't have any padding or margin for smaller screens

### ISSUE THREAD

**Issue by prashantsingh181** [MohammedMusharraf11/Alumni-Connect#24]
UI looks good in larger screen but for smaller screens main content doesn't have any padding or margin

<img width="376" alt="Screenshot 2024-10-27 at 11 42 24 AM" src="https://github.com/user-attachments/assets/d9866880-d338-4c98-bee2-733245029e65">

I would like to work on this issue. Can you please assign it to me?

**Comment by MohammedMusharraf11** [comment]
Sure @prashantsingh181

**Comment by MohammedMusharraf11** [comment]
@prashantsingh181 Can you please make Student and Alumni Registration page too responsive?
![image](https://github.com/user-attachments/assets/93e008d0-d123-4857-8731-469294acc168)

**Comment by prashantsingh181** [comment]
@MohammedMusharraf11 sure.

**Comment by prashantsingh181** [comment]
> Sure @prashantsingh181

@MohammedMusharraf11 Update the PR. Please check
