### ISSUE TITLE
Fix: File Upload in Student & Alumni Registration

### ISSUE THREAD

**Issue by MohammedMusharraf11** [MohammedMusharraf11/Alumni-Connect#26]

**Comment by JeetuSuthar** [comment]
Login signup page is not working 
i am getting error such as unable to fetch
@MohammedMusharraf11

**Comment by MohammedMusharraf11** [comment]
> Login signup page is not working i am getting error such as unable to fetch @MohammedMusharraf11

The deployed link actually doesn't has backend config you were supposed to run locally
