### ISSUE TITLE
Guidance Needed for "About Us" Page

### ISSUE THREAD

**Issue by JeetuSuthar** [MohammedMusharraf11/Alumni-Connect#34]
Hi! I’d like to enhance the "About Us" page and would appreciate your input. What key information or elements would you like included? Any specific style or content you prefer? Thanks!

**Comment by MohammedMusharraf11** [comment]
Can you just work on features tab and map it to the feature cards?
I will update About page later 
Thanks a lot for your valuable contributions (:

**Comment by JeetuSuthar** [comment]
I have made pr on feature tab
Can U plz elaborate if there is more any changes on that thing

**Comment by JeetuSuthar** [comment]
You are saying that When we click on Features the new page should open and it should show the features cards
I have already updated and send Pull req for this 
If something more req then tell

**Comment by MohammedMusharraf11** [comment]
can you just add some content to about page like some standard form later I will change and add the personal details

**Comment by JeetuSuthar** [comment]
@MohammedMusharraf11 ok I will do it today

**Comment by JeetuSuthar** [comment]
@MohammedMusharraf11 Done You can check pull req
